/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello Mr. Davis!";
    }

    public static void main(String[] args) {
        final App appInstance = new App();
        System.out.println(appInstance.getGreeting());
    }
}
